name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v4

    - name: Xcode Setup
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.1'

    - name: Build
  run: xcodebuild build -project ciCdHighWayToHell.xcodeproj -scheme ciCdHighWayToHell clean build -sdk iphoneos CODE_SIGNING_ALLOWED=No
