name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4

    - name: Xcode Setup
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'

    - name: Build
      run: |
        cd GitHubActions
        xcodebuild build -project ciCdHighwayToHell.xcodeproj -scheme ciCdHighwayToHell clean build -sdk iphoneos CODE_SIGNING_ALLOWED=No
